import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DataStorageProvider from "./context_providers/data_context/DataProvider";
import { ToastProvider } from './components/ToastContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="SeniorProject">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        id="root"
      >
        <DataStorageProvider>
          <ToastProvider>
            {children}
          </ToastProvider>
        </DataStorageProvider>
      </body>
    </html>
  );
}
